# Generated by Django 2.2.10 on 2020-04-27 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50, verbose_name='APP名称')),
                ('intro', models.TextField(verbose_name='介绍')),
                ('url', models.CharField(default='Https://', max_length=100, verbose_name='链接')),
                ('icon', models.ImageField(upload_to='images/', verbose_name='图标')),
                ('image', models.ImageField(upload_to='images/', verbose_name='图片')),
                ('votes', models.ImageField(default=1, upload_to='', verbose_name='投票数量')),
                ('pub_data', models.DateField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
