# Generated by Django 2.2.10 on 2020-04-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_data',
            field=models.DateTimeField(),
        ),
    ]
