# Generated by Django 2.2.10 on 2020-04-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200427_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votes',
            field=models.IntegerField(default=1, verbose_name='投票数量'),
        ),
    ]
